# Generated by Django 4.2.6 on 2024-04-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_bus_go_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
