# Generated by Django 4.2.6 on 2024-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_navbar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='heading',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='navbar',
            name='icon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
