# Generated by Django 4.2.6 on 2024-05-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_rename_heading_navbar_title_alter_navbar_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_whychoose',
            name='image1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bus_whychoose',
            name='image2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bus_whychoose',
            name='image3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bus_whychoose',
            name='image4',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bus_whychoose',
            name='image5',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
